force-app/main/default/objects/Trailblazer__c.object
<CustomObject>
    <description>A custom object to hold Trailhead profiles for the trailhead leaderboard.</description>
    <label>Trailblazer</label>
    <nameField>
        <label>Trailblazer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trailblazers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trailblazer__c/fields/Profile_Handle__c.field-meta.xml
<CustomField>
    <fullName>Profile_Handle__c</fullName>
    <description>The custom handle of the Trailblazer&#39;s profile on Trailhead (ex: &quot;matruff&quot;)</description>
    <externalId>true</externalId>
    <label>Profile Handle</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Profile_Id__c.field-meta.xml
<CustomField>
    <fullName>Profile_Id__c</fullName>
    <description>The Id of the Trailblazer&apos;s profile on Trailhead</description>
    <externalId>true</externalId>
    <label>Profile Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/PopulateTrailblazersTest.cls
/**
 * @description Unit Tests for PopulateTrailblazers.cls
 *
 * @author meruff
 *
 * @date 7/27/17
 */
@IsTest
private class PopulateTrailblazersTest {
    @IsTest
    static void testExecuteBatch() {
        Test.startTest();
        Database.executeBatch(new PopulateTrailblazers());
        Test.stopTest();
    }

    @IsTest
    static void testExecuteBatchWithScope() {
        insert new Trailblazer__c(
            Name = 'mat ruff',
            Profile_Handle__c = 'matruff'
        );

        Test.startTest();
        Database.executeBatch(
            new PopulateTrailblazers([
                SELECT Id,
                    Profile_Handle__c,
                    Profile_Id__c
                FROM Trailblazer__c
            ])
        );
        Test.stopTest();
    }

    @IsTest
    static void testSchedulePopulation() {
        Test.startTest();
        System.schedule(
            'Test Scheduling PopulateTrailblazers',
            '0 0 23 * * ?',
            new PopulateTrailblazers()
        );
        Test.stopTest();

        List<AsyncApexJob> assertScheduledJobs = [
            SELECT ApexClass.Name
            FROM AsyncApexJob
            WHERE JobType = 'ScheduledApex'
        ];

        Assert.areEqual('PopulateTrailblazers', assertScheduledJobs[0].ApexClass.Name, 'PopulateTrailblazers should be scheduled.');
        Assert.areEqual(1, assertScheduledJobs.size(), 'Only PopulateTrailblazers should be in the queue.');

        List<AsyncApexJob> assertBatchJobs = [
            SELECT ApexClass.Name
            FROM AsyncApexJob
            WHERE JobType = 'BatchApex'
        ];

        Assert.areEqual('PopulateTrailblazers', assertBatchJobs[0].ApexClass.Name, 'PopulateTrailblazers should be in the batch queue.');
        Assert.areEqual(1, assertBatchJobs.size(), 'Only PopulateTrailblazers should be in the queue.');
    }
}