force-app/main/default/objects/Trailblazer__c.object
<CustomObject>
    <description>A custom object to hold Trailhead profiles for the trailhead leaderboard.</description>
    <label>Trailblazer</label>
    <nameField>
        <label>Trailblazer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trailblazers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trailblazer__c/fields/Badges__c.field-meta.xml
<CustomField>
    <fullName>Badges__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of Trailhead Badges</description>
    <label>Badges</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Certifications__c.field-meta.xml
<CustomField>
    <fullName>Certifications__c</fullName>
    <description>Number of Salesforce Certifications</description>
    <label>Certifications</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Company_Institution__c.field-meta.xml
<CustomField>
    <fullName>Company_Institution__c</fullName>
    <label>Company/Institution</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <label>Job Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <label>Job Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <description>Number of Trailhead points</description>
    <label>Points</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Profile_Handle__c.field-meta.xml
<CustomField>
    <fullName>Profile_Handle__c</fullName>
    <description>The custom handle of the Trailblazer&#39;s profile on Trailhead (ex: &quot;matruff&quot;)</description>
    <externalId>true</externalId>
    <label>Profile Handle</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Profile_Id__c.field-meta.xml
<CustomField>
    <fullName>Profile_Id__c</fullName>
    <description>The Id of the Trailblazer&apos;s profile on Trailhead</description>
    <externalId>true</externalId>
    <label>Profile Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Profile_Link__c.field-meta.xml
<CustomField>
    <fullName>Profile_Link__c</fullName>
    <description>Link to the Trailblazer&#39;s profile on Trailhead</description>
    <label>Profile Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Profile_Photo__c.field-meta.xml
<CustomField>
    <fullName>Profile_Photo__c</fullName>
    <description>Trailhead profile photo</description>
    <label>Profile Photo</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <description>Trailhead Profile Rank</description>
    <label>Rank</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Rank_Badge_Link__c.field-meta.xml
<CustomField>
    <fullName>Rank_Badge_Link__c</fullName>
    <description>Link to the Trailblazer&#39;s rank badge image</description>
    <label>Rank Badge Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Superbadges__c.field-meta.xml
<CustomField>
    <fullName>Superbadges__c</fullName>
    <description>Number of Trailhead Superbadges</description>
    <label>Superbadges</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Trails__c.field-meta.xml
<CustomField>
    <fullName>Trails__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of Trailhead trails completed</description>
    <label>Trails</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GetTrailblazerInfoAsync.cls
/**
* @author meruff
* @date 5/29/20
*
* A helper class for calling out to the Trailhead API and populating Trailblazer__c records.
*/
public class GetTrailblazerInfoAsync implements Queueable, Database.AllowsCallouts {
    public static final String TRAILHEAD_ME = 'https://trailblazer.me/id/';
    public static final String TRAILHEAD_ME_USERID = 'https://trailblazer.me/id?cmty=trailhead&uid=';
    public static final String GO_TRAILHEAD_API = 'https://go-trailhead-leaderboard-api.herokuapp.com/trailblazer/';
    public static final String JOB_NAME = 'Populate Trailblazers from GetTrailblazerInfoAsync';
    public static final String PROFILE_PATH = '/profile';
    public static final String SUPERBADGES_PATH = '/badges/superbadge';
    public static final String CERTIFICATIONS_PATH = '/certifications';
    public static final String HEROKU_ERROR = 'Application error';
    public static final String SUCCESS = 'success';

    private Integer jobCount = 0;
    private List<Trailblazer__c> trailblazers;

    public GetTrailblazerInfoAsync(Integer count, List<Trailblazer__c> scope) {
        jobCount = count;
        trailblazers = scope;
    }

    public void execute(QueueableContext context) {
        if (trailblazers.isEmpty()) {
            return;
        }

        Trailblazer__c trailblazer = trailblazers[0];
        getProfileCountsData(trailblazer, buildCalloutURL(trailblazer, ''));
        getProfileData(trailblazer, buildCalloutURL(trailblazer, PROFILE_PATH));
        getSuperbadgeData(trailblazer, buildCalloutURL(trailblazer, SUPERBADGES_PATH));
        getCertificationData(trailblazer, buildCalloutURL(trailblazer, CERTIFICATIONS_PATH));

        if (!String.isBlank(trailblazer.Profile_Handle__c)) {
            upsert trailblazer Profile_Handle__c;
        }

        trailblazers.remove(0);
        jobCount++;

        if (!trailblazers.isEmpty()) {
            if (jobCount <= 4) {
                if (!Test.isRunningTest()) {
                    System.enqueueJob(new GetTrailblazerInfoAsync(jobCount, trailblazers));
                }
            } else {
                System.scheduleBatch(new PopulateTrailblazers(trailblazers), JOB_NAME, 0);
            }
        }
    }

    /**
     * Bulids the callout endpoint before calling doCallout() to get a JSON response.
     * 
     * @see doCallout()
     * 
     * @param trailblazer, the Trailblazer__c record to populate with response data.
     * @param path, the URL path to append to the end of the default callout URL i.e. '/certifications'.
     *
     * @return res.getBody(), the JSON response body returned from the endpoint.
     */
    public static String buildCalloutURL(Trailblazer__c trailblazer, String path) {
        String calloutURL = '';

        if (!String.isBlank(trailblazer.Profile_Handle__c)) {
            calloutURL = GO_TRAILHEAD_API + trailblazer.Profile_Handle__c + (!String.isBlank(path) ? path : '');
        } else {
            calloutURL = GO_TRAILHEAD_API + trailblazer.Profile_Id__c + (!String.isBlank(path) ? path : '');
        }

        return doCallout(calloutURL);
    }

    /**
     * Writes data from the /profile/ endpoint to the Trailblazer__c record.
     *
     * @param trailblazer, a Trailblazer__c record to write to.
     * 
     * @param resBody, the response body JSON to deserialize and write to the Trailblazer__c record.
     */
    public static String getProfileData(Trailblazer__c trailblazer, String resBody) {
        if (resBody.contains(HEROKU_ERROR) || String.isBlank(resBody)) {
            return buildErrorAsJSON('Application Error, please try again. API may be down.');
        }

        ProfileData data = (ProfileData) JSON.deserialize(resBody.replaceAll('__c', ''), ProfileData.class);
        
        if (!String.isBlank(data.error)) {
            return data.error;
        }

        if (data.profileUser != null) {
            trailblazer.Profile_Id__c = data.profileUser.Id;
            trailblazer.Name = data.profileUser.FirstName + ' ' + data.profileUser.LastName;
            trailblazer.Profile_Photo__c = data.profilePhotoUrl;
            trailblazer.Profile_Handle__c = data.profileUser.TrailblazerId;
            trailblazer.Company_Institution__c = data.profileUser.CompanyName;
            trailblazer.Job_Title__c = data.profileUser.Title;
            trailblazer.Job_Role__c = data.profileUser.TBID_Role;

            if (!String.isBlank(data.profileUser.TrailblazerId)) {
                trailblazer.Profile_Link__c = TRAILHEAD_ME + data.profileUser.TrailblazerId;
            } else {
                trailblazer.Profile_Link__c = TRAILHEAD_ME_USERID + data.profileUser.Id;
            }
        }
        
        return SUCCESS;
    }

    /**
     * Writes data from the /trailblazer/ endpoint to the Trailblazer__c record.
     *
     * @param trailblazer, a Trailblazer__c record to write to.
     * 
     * @param resBody, the response body JSON to deserialize and write to the Trailblazer__c record.
     */
    public static String getProfileCountsData(Trailblazer__c trailblazer, String resBody) {
        if (resBody.contains(HEROKU_ERROR) || String.isBlank(resBody)) {
            return buildErrorAsJSON('Application Error, please try again. API may be down.');
        }

        ProfileCountData data = (ProfileCountData) JSON.deserialize(resBody.replaceAll('__c', ''), ProfileCountData.class);

        if (!String.isBlank(data.error)) {
            return data.error;
        }
        
        if (data.value != null && !data.value.isEmpty() 
            && data.value[0].ProfileCounts != null 
            && !data.value[0].ProfileCounts.isEmpty()
        ) {
            trailblazer.Points__c = data.value[0].ProfileCounts[0].EarnedPointTotal;
            trailblazer.Badges__c = data.value[0].ProfileCounts[0].EarnedBadgeTotal;
            trailblazer.Trails__c = data.value[0].ProfileCounts[0].CompletedTrailTotal;
            trailblazer.Rank__c = data.value[0].ProfileCounts[0].RankLabel.capitalize();
            trailblazer.Rank_Badge_Link__c = data.value[0].ProfileCounts[0].RankImageUrl;
        }
        
        return SUCCESS;
    }

    /**
     * Writes data from the /trailblazer/ endpoint to the Trailblazer__c record.
     *
     * @param trailblazer, a Trailblazer__c record to write to.
     * 
     * @param resBody, the response body JSON to deserialize and write to the Trailblazer__c record.
     */
    public static String getSuperbadgeData(Trailblazer__c trailblazer, String resBody) {
        if (resBody.contains(HEROKU_ERROR) || String.isBlank(resBody)) {
            return buildErrorAsJSON('Application Error, please try again. API may be down.');
        }

        BadgeData data = (BadgeData) JSON.deserialize(resBody.replaceAll('__c', ''), BadgeData.class);

        if (!String.isBlank(data.error)) {
            return data.error;
        }

        if (data.value != null 
            && !data.value.isEmpty() 
            && data.value[0].EarnedAwards != null 
            && !data.value[0].EarnedAwards.isEmpty()
        ) {
            Integer count = 0;

            for (BadgeData.EarnedAwards award : data.value[0].EarnedAwards) {
                if (award.AwardType == 'Superbadge') count++;
            }

            trailblazer.Superbadges__c = count;
        }

        return SUCCESS;
    }

    /**
     * Writes data from the /trailblazer/ endpoint to the Trailblazer__c record.
     *
     * @param trailblazer, a Trailblazer__c record to write to.
     * 
     * @param resBody, the response body JSON to deserialize and write to the Trailblazer__c record.
     */
    public static String getCertificationData(Trailblazer__c trailblazer, String resBody) {
        if (resBody.contains(HEROKU_ERROR) || String.isBlank(resBody)) {
            return buildErrorAsJSON('Application Error, please try again. API may be down.');
        }

        CertificationData data = (CertificationData) JSON.deserialize(resBody.replaceAll('__c', ''), CertificationData.class);

        if (!String.isBlank(data.error)) {
            return data.error;
        }

        if (data != null 
            && data.certificationsList != null 
            && !data.certificationsList.isEmpty()
        ) {
            trailblazer.Certifications__c = data.certificationsList.size();
        }

        return SUCCESS;
    }

    /**
     * Creates a callout using the supplied URL.
     *
     * @param calloutURL, the URL to do a callout to.
     * 
     * @return res.getBody() the body of the callout response.
     */
    public static String doCallout(String calloutURL) {
        Http h = new Http();
        HttpRequest req = new HttpRequest();
        req.setEndpoint(calloutURL);
        req.setMethod('GET');
        req.setTimeout(60000);
        HttpResponse res = h.send(req);

        return res.getBody();
    }

    /**
     * Returns a JSON Error object from the provided message String.
     * 
     * @param message, the String to output as the Error message. 
     * 
     * @return a serialized GetTrailblazerInfoAsync.Error object.
     */
    private static String buildErrorAsJSON(String message) {
        return JSON.serialize(new Error(message));
    }

    class Error {
        public String error { get; set; }

        public Error(String message) {
            this.error = message;
        }
    }
}