force-app/main/default/objects/Trailblazer__c.object
<CustomObject>
    <description>A custom object to hold Trailhead profiles for the trailhead leaderboard.</description>
    <label>Trailblazer</label>
    <nameField>
        <label>Trailblazer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trailblazers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trailblazer__c/fields/Profile_Handle__c.field-meta.xml
<CustomField>
    <fullName>Profile_Handle__c</fullName>
    <description>The custom handle of the Trailblazer&#39;s profile on Trailhead (ex: &quot;matruff&quot;)</description>
    <externalId>true</externalId>
    <label>Profile Handle</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/GetTrailblazerInfoAsyncTest.cls
/**
* @author meruff
* @date 5/29/20
*
* Unit Tests for GetTrailblazerInfoAsyncTest
*/
@IsTest
private class GetTrailblazerInfoAsyncTest {
    @TestSetup
    static void setUpData() {
        insert new List<Trailblazer__c>{
            new Trailblazer__c(
                Name = 'mat ruff',
                Profile_Handle__c = 'matruff'
            ),
            new Trailblazer__c(
                Name = 'Test 1',
                Profile_Handle__c = 'test1'
            ),
            new Trailblazer__c(
                Name = 'Test 2',
                Profile_Handle__c = 'test2'
            ),
            new Trailblazer__c(
                Name = 'Test 3',
                Profile_Handle__c = 'test3'
            ),
            new Trailblazer__c(
                Name = 'Test 4',
                Profile_Handle__c = 'test4'
            ),
            new Trailblazer__c(
                Name = 'Test 5',
                Profile_Handle__c = 'test5'
            )
        };
    }

    @IsTest
    static void testBehavior() {
        // Arrange


        // Act 
        Test.startTest();

        Test.stopTest();

        // Assert
        System.assert(true);
    }
}