force-app/main/default/objects/Trailblazer__c.object
<CustomObject>
    <description>A custom object to hold Trailhead profiles for the trailhead leaderboard.</description>
    <label>Trailblazer</label>
    <nameField>
        <label>Trailblazer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trailblazers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trailblazer__c/fields/Profile_Handle__c.field-meta.xml
<CustomField>
    <fullName>Profile_Handle__c</fullName>
    <description>The custom handle of the Trailblazer&#39;s profile on Trailhead (ex: &quot;matruff&quot;)</description>
    <externalId>true</externalId>
    <label>Profile Handle</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Profile_Id__c.field-meta.xml
<CustomField>
    <fullName>Profile_Id__c</fullName>
    <description>The Id of the Trailblazer&apos;s profile on Trailhead</description>
    <externalId>true</externalId>
    <label>Profile Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/PopulateTrailblazers.cls
/**
 * @description A class to populate Trailblazer__c records in batch.
 *
 * @author meruff
 *
 * @date 3/10/20
 */
public class PopulateTrailblazers implements Database.Batchable<SObject>, Database.Stateful, Schedulable {
    private final List<Trailblazer__c> trailblazers;

    public PopulateTrailblazers() {
        trailblazers = new List<Trailblazer__c>();
    }

    public PopulateTrailblazers(List<Trailblazer__c> scope) {
        trailblazers = scope;
    }

    public Database.QueryLocator start(Database.BatchableContext batchableContext) {
        String queryString = 'SELECT Profile_Handle__c, Profile_Id__c FROM Trailblazer__c';

        if (trailblazers != null && !trailblazers.isEmpty()) {
            queryString += ' WHERE Id IN: trailblazers';
        }

        return Database.getQueryLocatorWithBinds(
            queryString,
            new Map<String, Object>{ 'trailblazers' => trailblazers },
            AccessLevel.SYSTEM_MODE
        );
    }

    public void execute(SchedulableContext schedulableContext) {
        Database.executeBatch(new PopulateTrailblazers());
    }

    public void execute(Database.BatchableContext batchableContext, List<SObject> scope) {
        if (!Test.isRunningTest()) {
            System.enqueueJob(new GetTrailblazerInfoAsync(0, scope));
        }
    }

    public void finish(Database.BatchableContext batchableContext) {
    }
}