force-app/main/default/objects/Trailblazer__c.object
<CustomObject>
    <description>A custom object to hold Trailhead profiles for the trailhead leaderboard.</description>
    <label>Trailblazer</label>
    <nameField>
        <label>Trailblazer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trailblazers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trailblazer__c/fields/Badges__c.field-meta.xml
<CustomField>
    <fullName>Badges__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of Trailhead Badges</description>
    <label>Badges</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Certifications__c.field-meta.xml
<CustomField>
    <fullName>Certifications__c</fullName>
    <description>Number of Salesforce Certifications</description>
    <label>Certifications</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Company_Institution__c.field-meta.xml
<CustomField>
    <fullName>Company_Institution__c</fullName>
    <label>Company/Institution</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <label>Job Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <label>Job Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <description>Number of Trailhead points</description>
    <label>Points</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Profile_Handle__c.field-meta.xml
<CustomField>
    <fullName>Profile_Handle__c</fullName>
    <description>The custom handle of the Trailblazer&#39;s profile on Trailhead (ex: &quot;matruff&quot;)</description>
    <externalId>true</externalId>
    <label>Profile Handle</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Profile_Id__c.field-meta.xml
<CustomField>
    <fullName>Profile_Id__c</fullName>
    <description>The Id of the Trailblazer&apos;s profile on Trailhead</description>
    <externalId>true</externalId>
    <label>Profile Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Profile_Link__c.field-meta.xml
<CustomField>
    <fullName>Profile_Link__c</fullName>
    <description>Link to the Trailblazer&#39;s profile on Trailhead</description>
    <label>Profile Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Profile_Photo__c.field-meta.xml
<CustomField>
    <fullName>Profile_Photo__c</fullName>
    <description>Trailhead profile photo</description>
    <label>Profile Photo</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <description>Trailhead Profile Rank</description>
    <label>Rank</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Rank_Badge_Link__c.field-meta.xml
<CustomField>
    <fullName>Rank_Badge_Link__c</fullName>
    <description>Link to the Trailblazer&#39;s rank badge image</description>
    <label>Rank Badge Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Superbadges__c.field-meta.xml
<CustomField>
    <fullName>Superbadges__c</fullName>
    <description>Number of Trailhead Superbadges</description>
    <label>Superbadges</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Trailblazer_Since__c.field-meta.xml
<CustomField>
    <fullName>Trailblazer_Since__c</fullName>
    <description>The date the Trailblazer started Trailhead</description>
    <label>Trailblazer Since</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Trails__c.field-meta.xml
<CustomField>
    <fullName>Trails__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of Trailhead trails completed</description>
    <label>Trails</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TrailheadLeaderboardAuraController.cls
/**
* @author meruff
* @date 2019-06-17
*
* Apex controller logic for LWC leaderboard.
*/
public without sharing class TrailheadLeaderboardAuraController {
    /**
     * Queries for Trailblazer__c records to display on the page.
     *
     * @param fieldToSortBy, the API Name of the field used to sort, defaults to Points__c.
     * @param descending, whether or not to sort by DESC.
     *
     * @return a List of Trailblazer__c records.
     */
    @AuraEnabled(Cacheable=true)
    public static List<Trailblazer__c> populateTrailblazers(String fieldToSortBy, Boolean descending) {
        String queryString = '' +
            'SELECT Id, Name, Badges__c, Points__c, Trailblazer_Since__c, Trails__c, Profile_Handle__c, Profile_Id__c, ' +
                'Profile_Link__c, Rank__c, Profile_Photo__c, Job_Role__c, Job_Title__c, Company_Institution__c, ' +
                'Rank_Badge_Link__c, Superbadges__c, Certifications__c, LastModifiedDate ' +
            'FROM Trailblazer__c ' +
            'WHERE Points__c != NULL ' +
            'AND Rank__c != NULL';

        if (String.isBlank(fieldToSortBy)) {
            queryString += ' ORDER BY Points__c DESC';
        } else {
            queryString += ' ORDER BY ' + fieldToSortBy;

            if (descending == null || descending) {
                queryString += ' DESC';
            } else {
                queryString += ' ASC';
            }
        }

        return Database.query(queryString);
    }

    /**
     * Creates and upserts a new Trailblazer__c record by calling out to the Trailhead API and parsing the response data.
     *
     * @param userId, the user handle to use when calling out to Trailhead.
     *
     * @return, a message String whether or not the callout succeeded.
     */
    @AuraEnabled
    public static String createTrailblazer(String userId) {
        Trailblazer__c newTrailblazer = new Trailblazer__c(Profile_Handle__c = userId.replace(' ', '').trim());

        for (String s : new Set<String>{
            GetTrailblazerInfoAsync.getProfileCountsData(newTrailblazer, GetTrailblazerInfoAsync.buildCalloutURL(newTrailblazer, '')),
            GetTrailblazerInfoAsync.getProfileData(newTrailblazer, GetTrailblazerInfoAsync.buildCalloutURL(newTrailblazer, GetTrailblazerInfoAsync.PROFILE_PATH)),
            GetTrailblazerInfoAsync.getSuperbadgeData(newTrailblazer, GetTrailblazerInfoAsync.buildCalloutURL(newTrailblazer, GetTrailblazerInfoAsync.SUPERBADGES_PATH)),
            GetTrailblazerInfoAsync.getCertificationData(newTrailblazer, GetTrailblazerInfoAsync.buildCalloutURL(newTrailblazer, GetTrailblazerInfoAsync.CERTIFICATIONS_PATH))
        }) {
            if (!s.equals(GetTrailblazerInfoAsync.SUCCESS)) {
                return s;
            }
        }

        try {
            upsert newTrailblazer Profile_Handle__c;
            return 'success';
        } catch(Exception e) {
            return 'Error creating Trailblazer__c. Please try again.';
        }
    }

    /**
     * Returns a List of BadgeData.EarnedAwards records after parsing the response data from the Trailhead API.
     *
     * @param userId, the user handle to use when calling out to Trailhead.
     *
     * @return, a List of BadgeData.EarnedAwards records.
     */
    @AuraEnabled
    public static List<BadgeData.EarnedAwards> getBadgeData(String userId, String filter, String offset) {
        String calloutURL = '';

        if (!String.isBlank(filter)) {
            calloutURL = GetTrailblazerInfoAsync.GO_TRAILHEAD_API + userId + '/badges/' + filter;

            if (!String.isBlank(offset)) {
                calloutURL += '/' + offset;
            }
        } else {
            calloutURL = GetTrailblazerInfoAsync.GO_TRAILHEAD_API + userId + 'badges';
        }

        HttpResponse res = doCallout(calloutURL);

        if (res.getBody().contains('application-error')) {
            return null;
        }

        BadgeData data = (BadgeData) JSON.deserialize(res.getBody().replaceAll('__c', ''), BadgeData.class);

        if (String.isBlank(data.error)
            && data.value != null 
            && !data.value.isEmpty() 
            && data.value[0].EarnedAwards != null 
            && !data.value[0].EarnedAwards.isEmpty()
        ) {
            return data.value[0].EarnedAwards;
        } else {
            return null;
        }
    }

    /**
     * Returns a List of ProfileCountData.LearnedSkills records after parsing the response data from the Trailhead API.
     *
     * @param userId, the user handle to use when calling out to Trailhead.
     *
     * @return, a List of ProfileCountData.LearnedSkills records.
     */
    @AuraEnabled
    public static List<ProfileCountData.LearnedSkills> getSkillData(String userId) {
        HttpResponse res = doCallout(GetTrailblazerInfoAsync.GO_TRAILHEAD_API + userId);

        if (res.getBody().contains('application-error')) {
            return null;
        }

        ProfileCountData data = (ProfileCountData) JSON.deserialize(res.getBody().replaceAll('__c', ''), ProfileCountData.class);

        if (String.isBlank(data.error) 
            && data.value != null 
            && !data.value.isEmpty() 
            && data.value[0].LearnedSkills != null 
            && !data.value[0].LearnedSkills.isEmpty()
        ) {
            return data.value[0].LearnedSkills;
        } else {
            return null;
        }
    }

    /**
     * Returns a List of CertificationData.cerificationsList records after parsing the response data from the Trailhead API.
     *
     * @param userId, the user handle to use when calling out to Trailhead.
     *
     * @return, a List of CertificationData.certificationsList records.
     */
    @AuraEnabled
    public static List<CertificationData.certificationsList> getCertificationData(String userId) {
        HttpResponse res = doCallout(GetTrailblazerInfoAsync.GO_TRAILHEAD_API + userId + '/certifications');

        if (res.getBody().contains('application-error')) {
            return null;
        }

        CertificationData data = (CertificationData) JSON.deserialize(res.getBody().replaceAll('__c', ''), CertificationData.class);

        if (String.isBlank(data.error) 
            && data != null 
            && data.certificationsList != null 
            && !data.certificationsList.isEmpty()
        ) {
            return data.certificationsList;
        } else {
            return null;
        }
    }

    /**
     * Does a callout with the provided URL. 
     * 
     * @param calloutURL, the URL to call out to.
     * 
     * @return a HttpResponse from the callout.
     */
    public static HttpResponse doCallout(String calloutURL) {
        Http h = new Http();
        HttpRequest req = new HttpRequest();
        req.setEndpoint(calloutURL);
        req.setMethod('GET');
        req.setTimeout(60000);
        HttpResponse res = h.send(req);

        return res;
    }
}