src/objects/Badge__c.object
<CustomObject>
    <fields>
        <fullName>Date_Earned__c</fullName>
        <label>Date Earned</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Icon_Link__c</fullName>
        <label>Icon Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Path__c</fullName>
        <description>Link to badge on Trailhead</description>
        <label>Path</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Points__c</fullName>
        <label>Points</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trailblazer__c</fullName>
        <label>Trailblazer</label>
        <referenceTo>Trailblazer__c</referenceTo>
        <relationshipLabel>Badges</relationshipLabel>
        <relationshipName>Badges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Badge</label>
    <nameField>
        <label>Badge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Badges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Badge__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The full title of the Badge taken from Trailhead.</description>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Trailblazer__c.object
<CustomObject>
    <description>A custom object to hold Trailhead profiles for the trailhead leaderboard.</description>
    <fields>
        <fullName>Badges__c</fullName>
        <description>Number of Trailhead Badges</description>
        <label>Badges</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Company_Institution__c</fullName>
        <label>Company/Institution</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Role__c</fullName>
        <label>Job Role</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Title__c</fullName>
        <label>Job Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Points__c</fullName>
        <description>Number of Trailhead points</description>
        <label>Points</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Profile_Id__c</fullName>
        <description>The Id of the Trailblazer&apos;s profile on Trailhead</description>
        <externalId>true</externalId>
        <label>Profile Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Profile_Link__c</fullName>
        <description>Link to the Trailblazer&apos;s profile on Trailhead</description>
        <label>Profile Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Profile_Photo__c</fullName>
        <description>Trailhead profile photo</description>
        <label>Profile Photo</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <description>Trailhead Profile Rank</description>
        <label>Rank</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trailblazer_Since__c</fullName>
        <description>The date the Trailblazer started Trailhead</description>
        <label>Trailblazer Since</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trails__c</fullName>
        <description>Number of Trailhead trails completed</description>
        <label>Trails</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Trailblazer</label>
    <nameField>
        <label>Trailblazer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trailblazers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TrailheadLeaderboardAuraController.cls
/**
* @author Mathew Ruff, Sierra-Cedar
* @date 2019-06-17
*
* Apex controller logic for LWC leaderboard.
*/
public class TrailheadLeaderboardAuraController {
    @AuraEnabled(Cacheable=true)
    public static List<Trailblazer__c> populateTrailblazers() {
        return [
            SELECT Id, Name, Badges__c, Points__c, Trailblazer_Since__c, Trails__c, Profile_Id__c,
                Profile_Link__c, Rank__c, Profile_Photo__c, Job_Role__c, Job_Title__c, Company_Institution__c, (
                SELECT Title__c, Icon_Link__c, Type__c, Points__c, Date_Earned__c, Path__c
                FROM Badges__r
                ORDER BY Title__c ASC
            )
            FROM Trailblazer__c
            ORDER BY Points__c DESC
        ];
    }
}