src/objects/Badge__c.object
<CustomObject>
    <fields>
        <fullName>Date_Earned__c</fullName>
        <label>Date Earned</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Icon_Link__c</fullName>
        <label>Icon Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Path__c</fullName>
        <description>Link to badge on Trailhead</description>
        <label>Path</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Points__c</fullName>
        <label>Points</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trailblazer__c</fullName>
        <label>Trailblazer</label>
        <referenceTo>Trailblazer__c</referenceTo>
        <relationshipLabel>Badges</relationshipLabel>
        <relationshipName>Badges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Upsert_Key__c</fullName>
        <description>Trailblazer Id + api_name from Trailhead</description>
        <externalId>true</externalId>
        <label>Upsert Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Badge</label>
    <nameField>
        <label>Badge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Badges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Badge__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The full title of the Badge taken from Trailhead.</description>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Trailblazer__c.object
<CustomObject>
    <description>A custom object to hold Trailhead profiles for the trailhead leaderboard.</description>
    <fields>
        <fullName>Badges__c</fullName>
        <description>Number of Trailhead Badges</description>
        <label>Badges</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Company_Institution__c</fullName>
        <label>Company/Institution</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Role__c</fullName>
        <label>Job Role</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Title__c</fullName>
        <label>Job Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Points__c</fullName>
        <description>Number of Trailhead points</description>
        <label>Points</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Profile_Id__c</fullName>
        <description>The Id of the Trailblazer&apos;s profile on Trailhead</description>
        <externalId>true</externalId>
        <label>Profile Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Profile_Link__c</fullName>
        <description>Link to the Trailblazer&apos;s profile on Trailhead</description>
        <label>Profile Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Profile_Photo__c</fullName>
        <description>Trailhead profile photo</description>
        <label>Profile Photo</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <description>Trailhead Profile Rank</description>
        <label>Rank</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trailblazer_Since__c</fullName>
        <description>The date the Trailblazer started Trailhead</description>
        <label>Trailblazer Since</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trails__c</fullName>
        <description>Number of Trailhead trails completed</description>
        <label>Trails</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Trailblazer</label>
    <nameField>
        <label>Trailblazer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trailblazers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TrailheadLeaderboardController.cls
/*****************************************
* File: TrailheadLeaderboardController
* Author: meruff
* Description: Controller class for trailheadLeaderboard.page
******************************************/
public class TrailheadLeaderboardController {
    private Set<String> trailblazerIds;
    public List<Trailblazer__c> trailblazers { get; set; }
    public Map<String, List<Badge__c>> badgesMap { get; set; }
    public String newProfileId { get; set; }
    public String selectedName { get; set; }
    public String selectedId { get; set; }

    public TrailheadLeaderboardController() {
        populateTrailblazers();
    }

    /**
     * Queries for current Trailblazer__c records to display on the Visualforce page.
     */
    public void populateTrailblazers() {
        newProfileId = '';
        trailblazerIds = new Set<String>();
        badgesMap = new Map<String, List<Badge__c>>();

        trailblazers = new List<Trailblazer__c>([
            SELECT Id, Name, Badges__c, Points__c, Trailblazer_Since__c, Trails__c, Profile_Id__c,
                Profile_Link__c, Rank__c, Profile_Photo__c, Job_Role__c, Job_Title__c, Company_Institution__c, (
                SELECT Title__c, Icon_Link__c, Type__c, Points__c, Date_Earned__c, Path__c
                FROM Badges__r
                ORDER BY Date_Earned__c DESC NULLS LAST
            )
            FROM Trailblazer__c
            ORDER BY Points__c DESC
        ]);

        for (Trailblazer__c tb : trailblazers) {
            trailblazerIds.add(tb.Profile_Id__c);

            for (Badge__c badge : tb.Badges__r) {
                if (!badgesMap.containsKey(tb.Profile_Id__c)) {
                    badgesMap.put(tb.Profile_Id__c, new List<Badge__c>{badge});
                } else {
                    badgesMap.get(tb.Profile_Id__c).add(badge);
                }
            }
        }
    }

    /**
     * Creates a new Trailblazer record to upsert into Salesforce by calling out to Trailhead with the provided profile
     * Id on the Visualforce page.
     */
    public PageReference upsertNewTrailblazer() {
        try {
            findAndUpsertTrailblazer(newProfileId);
            populateTrailblazers();
            PageReference refresh = new PageReference('/trailheadLeaderboard');
            refresh.setRedirect(true);
            return refresh;
        } catch(Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,
                ' Error during callout to Trailhead, please try again. ' + e.getMessage()));
            return null;
        }
    }

    /**
     * Calls out to Trailhead and attempts to find the Trailblazer by the profile Id provided.
     *
     * @param profileId, the public Trailhead profile Id for the user.
     * @return tbToUpsert, the Trailblazer__c record to upsert into Salesforce.
     */
    public void findAndUpsertTrailblazer(String profileId) {
        Http h = new Http();
        HttpRequest req = new HttpRequest();
        req.setEndpoint(PopulateTrailblazers.TRAILHEAD_URL + '/me/' + profileId);
        req.setMethod('GET');
        HttpResponse res = h.send(req);

        // Handling for redirects (custom Trailhead Profiles /me/)
        Boolean redirect = false;

        if (res.getStatusCode() >= 300 && res.getStatusCode() <= 307 && res.getStatusCode() != 306) {
            do {
                redirect = false; // reset the value each time
                String loc = res.getHeader('Location'); // get location of the redirect

                if (loc == null) {
                    redirect = false;
                    continue;
                }

                req = new HttpRequest();
                req.setEndpoint(loc);
                req.setMethod('GET');
                res = h.send(req);

                if (res.getStatusCode() != 500) { // 500 = fail
                    if (res.getStatusCode() >= 300 && res.getStatusCode() <= 307 && res.getStatusCode() != 306) {
                        redirect = true;
                    }
                }
            } while (redirect && Limits.getCallouts() != Limits.getLimitCallouts());
        }

        if (res.getStatus() != 'Not Found'
            && (!res.getBody().contains('Someone\'s hiding!')
            && !res.getBody().contains('This user has chosen to keep their profile private.'))
        ) {
            Trailblazer__c tbToUpsert = PopulateTrailblazers.populateTrailblazer(res.getBody());
            upsert tbToUpsert Profile_Id__c;

            List<Badge__c> badgesToUpsert = PopulateTrailblazers.getTrailblazerBadges(res.getBody(), tbToUpsert);
            if (badgesToUpsert.size() > 0) {
                upsert badgesToUpsert Upsert_Key__c;
            }
        } else {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,
                'Could not find a Trailhead profile for User Id: ' + profileId +
                '. Please ensure your profile is set to public and you\'ve copied your Id correctly.'
            ));
            return;
        }
    }

    public Boolean getIsMapEmpty() {
        return (badgesMap.get(selectedId) == null || badgesMap.get(selectedId).size() == 0);
    }
}