src/objects/Trailblazer__c.object
<CustomObject>
    <description>A custom object to hold Trailhead profiles for the trailhead leaderboard.</description>
    <fields>
        <fullName>Badges__c</fullName>
        <description>Number of Trailhead Badges</description>
        <label>Badges</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Points__c</fullName>
        <description>Number of Trailhead points</description>
        <label>Points</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Profile_Id__c</fullName>
        <description>The Id of the Trailblazer&apos;s profile on Trailhead</description>
        <externalId>true</externalId>
        <label>Profile Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Profile_Photo__c</fullName>
        <description>Trailhead profile photo</description>
        <label>Profile Photo</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Trailblazer_Since__c</fullName>
        <description>The date the Trailblazer started Trailhead</description>
        <label>Trailblazer Since</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trails__c</fullName>
        <description>Number of Trailhead trails completed</description>
        <label>Trails</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Trailblazer</label>
    <nameField>
        <label>Trailblazer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trailblazers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TrailheadLeaderboardControllerTest.cls
/*****************************************
* File: TrailheadLeaderboardControllerTest
* Author: detonation0
* Description: Unit tests for TrailheadLeaderboardControllerTest.cls
******************************************/
@isTest
private class TrailheadLeaderboardControllerTest {
    @testSetup static void setUpData() {
        Trailblazer__c newBlazer = new Trailblazer__c(
            Name = 'Some ExistingBlazer',
            Profile_Id__c = '005500000061jCZBBY',
            Points__c = 450,
            Trails__c = 8,
            Trailblazer_Since__c = 'September 17th, 2000',
            Profile_Photo__c = 'https://trailhead.com/photourl'
        );
        insert newBlazer;
    }

    static testMethod void testAddTrailblazer() {
        // Arrange
        Test.setMock(HttpCalloutMock.class, new TrailheadCalloutMock());
        Test.setCurrentPage(Page.trailheadLeaderboard);

        // Act
        Test.startTest();
        TrailheadLeaderboardController tlb = new TrailheadLeaderboardController();
        tlb.newBlazer.Profile_Id__c = '005500000061jCZBBY'; // Throws existing user error
        tlb.upsertNewTrailblazer();
        tlb.newBlazer.Profile_Id__c = '005500000061jCZAA'; // Throws length error
        tlb.upsertNewTrailblazer();
        tlb.newBlazer.Profile_Id__c = '005500000061jCZAAY'; // Should succeed.
        tlb.upsertNewTrailblazer();
        Test.stopTest();

        // Assert
        Trailblazer__c assertTrailblazer = [
            SELECT Name, Badges__c, Trails__c
            FROM Trailblazer__c
            WHERE Profile_Id__c = '005500000061jCZAAY'
        ];

        System.assertEquals('Detonation', assertTrailblazer.Name,
            'Name should have been upserted to Detonation. Capitalized and numbers removed.');
        System.assertEquals(45, assertTrailblazer.Badges__c,
            'Badges__c should have been upserted to 45');
        System.assertEquals(5, assertTrailblazer.Trails__c,
            'Trails__c should have been upserted to 5');
    }
}